# Generated by Django 6.0.1 on 2026-02-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('Productprice', models.IntegerField()),
                ('ProductDscription', models.TextField()),
                ('Productstock', models.PositiveIntegerField()),
                ('Productcolor', models.CharField(max_length=20, null=True)),
                ('Productstatus', models.BooleanField(default=True)),
            ],
        ),
    ]
