# Generated by Django 6.0.2 on 2026-02-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holderNname', models.CharField(max_length=50)),
                ('holderAge', models.IntegerField()),
                ('holderpassword', models.IntegerField()),
                ('holdercity', models.CharField(max_length=50)),
                ('holdergender', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'accountholder',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=100)),
                ('personcomment', models.TextField()),
                ('personage', models.IntegerField()),
                ('personcontect', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='service',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table=None,
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankBranch', models.CharField(max_length=50)),
                ('accounttype', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
                ('accountNumber', models.IntegerField()),
                ('signcher', models.CharField(max_length=50)),
                ('accountholderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.accountholder')),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='adharcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personcity', models.CharField(max_length=50)),
                ('persongender', models.CharField(max_length=12)),
                ('mastercardNumber', models.IntegerField()),
                ('password', models.IntegerField()),
                ('personId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.person')),
            ],
            options={
                'db_table': 'adharcard',
            },
        ),
    ]
