# Generated by Django 6.0.1 on 2026-02-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=50)),
                ('personAddress', models.CharField(max_length=50)),
                ('personpassword', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='adharcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personage', models.IntegerField()),
                ('personcity', models.CharField(max_length=50)),
                ('personISactive', models.BooleanField(default=True)),
                ('personAdharNumber', models.CharField(max_length=12)),
                ('personId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.person')),
            ],
        ),
    ]
